
    
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: nodejs-thumbnailer
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/evry-bergen/knative-workshop/
              revision: 6-buildpack-eventing
          template:
            name: knative-node10-runtime
            arguments:
            - name: IMAGE
              value: eu.gcr.io/knative-workshop-2019/lab-6-nodejs
            - name: DIRECTORY
              value: ./labs/6-buildpack-eventing/
            - name: HANDLER
              value: thumbnailCreator.thumbnailCreator
      revisionTemplate:
        spec:
          container:
            image: eu.gcr.io/knative-workshop-2019/lab-6-nodejs:latest
