# Replace the following before applying this file:
#   PROJECT: Replace with the GCP Project's ID.

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GcpPubSubSource
metadata:
  name: testing-source
spec:
  gcpCredsSecret:  # A secret in the knative-sources namespace
    name: gcp-pubsub-key
    key: key.json
  googleCloudProject: PROJECT # Replace this
  topic: testing
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: pubsub-test
