apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: lab-2-build
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/mchmarny/simple-app.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: eu.gcr.io/{PROJECT}/lab-2-build:latest
          timeout: 10m
      revisionTemplate:
        spec:
          container:
            image: eu.gcr.io/(PROJECT}/lab-2-build:latest
            imagePullPolicy: Always
            env:
              - name: SIMPLE_MSG
                value: "Hello from knative function built with kaniko!"
